In [ ]:
"""
k-邻近算法介绍：
k邻近法（k-nearest neighbor, k-NN）是1967年由Cover T和Hart P提出的一种基于分类和回归方法。
它的工作原理：存在一个样本数据集合，也称作为训练样本集，并且样本集中每个数据都存在标签，
即我们知道样本集中每一个数据与所属分类的对应关系。输入没有标签的新数据后，将新的数据的每个特征
与样本集中数据对应的特征进行比较，然后算法提取样本最相似数据（最邻近）的分类标签。一般来说，
我们只选择样本数据集中前k个最相似的数据，这就是k-邻近算法中k的出处，通常k是不大于20的整数。
最后，选择k个最相似数据中出现次数最多的分类，作为新数据的分类。
"""


In [6]:
import numpy as np
import operator
"""
函数说明：创建数据集
Parameters:
    无
Returns:
    group - 数据集
    labels - 分类标签
Modify:
    2022-05-24
"""
def createDataSet():
    # 四组二维特征
    group = np.array([[1, 101],[5, 89],[108, 5],[115, 8]])
    # 四组特征的标签
    labels = ['爱情片','爱情片','动作片','动作片']
    return group, labels

"""
函数说明：kNN算法，分类器
Parameters:
    inX - 用于分类的数据（测试集）
    dataSet - 用于训练的数据（训练集）
    labels - 分类标签
    k - kNN算法参数，选择距离最小的k个点
Returns:
    sortedClassCount[0][0] - 分类结果
Modify:
    2022-05-24
"""
def classify0(inX, dataSet, labels, k):
    # numpy函数shape[0]返回dataSet的行数
    dataSetSize = dataSet.shape[0]
    # 在列向量方向上重复inX共1次（横向），行向量方向上重复inX共dataSetSize次（纵向）
    diffMat = np.tile(inX, (dataSetSize, 1)) - dataSet
    # 二维特征相减后平方
    sqDiffMat = diffMat**2
    # sum()所有元素相加，sum(0)列相加，sum(1)行相加
    sqDistances = sqDiffMat.sum(axis=1)
    # 开方，计算出距离
    distances = sqDistances**0.5
    # 返回distances中元素从小到大排序后的所引值
    sortedDistIndices = distances.argsort()
    # 定一个记录类别次数的字典
    classCount = {}
    for i in range(k):
        # 取出前k个元素的类别
        voteIlabel = labels[sortedDistIndices[i]]
        # dict.get(key,default=None)，字典的get()方法，返回指定键的值，如果值不再字典中返回
        # 计算类别次数
        classCount[voteIlabel] = classCount.get(voteIlabel,0) + 1
    # python3中用items()替换python2中的iteritems()
    # key=operator.itemgetter(1)根据字典的值进行排序
    # key=operator.itemgetter(0)根据字典的键进行排序
    # reverse降序排序字典
    sortedClassCount = sorted(classCount.items(), key=operator.itemgetter(1), reverse=True)
    return sortedClassCount[0][0]


if __name__ == '__main__':
    # 创建数据集
    group, labels = createDataSet()
    # 测试集
    test = [101, 20]
    # KNN分类
    test_class = classify0(test, group, labels, 3)
    print(test_class)
    # 打印数据集
    #print(group)
    #print(labels)

动作片


In [3]:
'''
测试np.tile()函数，该函数用来扩展矩阵
'''
import numpy as np
a = np.array(
    [
        [1,2,3],
        [5,4,3],
        [7,8,9]
    ]
)

print(np.tile(a,2))
print(np.tile(a,(2,1)))

[[1 2 3 1 2 3]
 [5 4 3 5 4 3]
 [7 8 9 7 8 9]]
[[1 2 3]
 [5 4 3]
 [7 8 9]
 [1 2 3]
 [5 4 3]
 [7 8 9]]
